# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a7f999627167eb63d657037d575bc3f274588082b8e531f31f241e151da928b33e877dd92fdd277311b3fe55345712db13fcc7ea00a416410e0af6f6e532c6e

test:
  secret_key_base: d9d9d90e08388c4c88e7966d75c4e1ba21b8081fa46c85d87c925797d9447b195e847f61febeb87efad2ac36c799c1304d91d4e4837ebac083a45464bc863acf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
